### PR TITLE
Add a global url validator

### PR DESCRIPTION
**Pull request by luisherranz**

### CODE REVIEW

**Comment by lukejagodzinski** [comment]
Nice! Thanks, I will publish it in the next release. The RegExp is your own creation or did you take it from somewhere else?

**Comment by luisherranz** [comment]
I took it from somewhere, don't remember. I have been using it for a while, but it would be great to do some tests. I would have added some, but it looks like you don't have any tests for your other validators. Is that something you want to address? Or are you testing them somehow?

**Comment by lukejagodzinski** [comment]
Ok, I've just checked several options and it was validating correctly. It should be ok, but in deed it would be nice to have tests for all validators. Right now around 90% of Astronomy is covered with tests. I want it to improve for Astronomy 2.0. So if you would like to help with that in the future, then let me know :)

I don't have tests for validators. But they are simple enough that most of the don't need them, but anyway having tests would be great.

**Comment by luisherranz** [comment]
Ok, I see your are using Tinytest for Astronomy. That should be enough :+1:

**Pull request merged**
